### ISSUE TITLE
404/500 error pages

### ISSUE THREAD

**Issue by Lartza** [Lartza/SBbrowser#1]
Currently the website shows ugly 404 and 500 pages on errors.

~~500 errors are relatively common (on sb.ltn.fi at least) when the database migration happens so should probably handle that somehow cleanly for the user and note to refresh in a bit.~~ Not true anymore

**Comment by Lartza** [comment]
For the 500

```
Traceback (most recent call last):
  File "/srv/sponsorblock/SBtools/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/srv/sponsorblock/SBtools/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/sponsorblock/SBtools/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/sponsorblock/SBtools/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/sponsorblock/SBtools/venv/lib/python3.8/site-packages/django_filters/views.py", line 85, in get
    context = self.get_context_data(filter=self.filterset,
  File "/srv/sponsorblock/SBtools/browser/views.py", line 64, in get_context_data
    context['updated'] = updated()
  File "/srv/sponsorblock/SBtools/browser/views.py", line 14, in updated
    return isoparse(Config.objects.get(key='updated').value).strftime('%Y-%m-%d %H:%M:%S')
  File "/srv/sponsorblock/SBtools/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/sponsorblock/SBtools/venv/lib/python3.8/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
browser.models.Config.DoesNotExist: Config matching query does not exist.
```
